### ISSUE TITLE
[Feature Request] A Left Pane(like Backlink Pane) to Show Relative Notes Like Devonthink

### ISSUE THREAD

**Issue by Quorafind** [ryanjamurphy/DEVONlink-obsidian#1]
If we can view the notes associated with our notes directly from the sidebar, we can take advantage of the other features of Ob and only use the SEE ALSO function of DEVONthink.

**Comment by ryanjamurphy** [comment]
Thanks for the request! However, I don't plan on implementing this—my goal isn't to replicate DEVONthink inside Obsidian, but to find ways to leverage the unique features of each. It's also outside of my UI/front-end development capabilities at the moment.

I suggest using the "Reveal in DEVONthink" command to jump to the record, and to bring up the See Also pane in DEVONthink when there.

**Comment by Quorafind** [comment]
Thanks for reply
