### ISSUE TITLE
Cannot update because the style.css isn't packaged.

### ISSUE THREAD

**Issue by Quorafind** [ryanjamurphy/DEVONlink-obsidian#13]

**Comment by jsmm** [comment]
The new version cannot be installed in macOS 11.4.
As it couldn't updtate, I tried to reintall it, aind it fails to install.

**Comment by wenlzhang** [comment]
Not sure if it is related to the fact that, from within Obsidian, the version is 2.2.1, but the latest release here is version 2.2.0.

**Comment by ryanjamurphy** [comment]
Whoops. Good catch, @wenlzhang. Fixed! Sorry all!
