### ISSUE TITLE
Can you provide a "devonlink-integrate-obsidian-and-devonthink" AppleScript file?

### ISSUE THREAD

**Issue by aemsuoqso7816** [ryanjamurphy/DEVONlink-obsidian#20]
Can you provide the plugin files for Devonthink? I've searched around the web and can't find it, and [devonlink-integrate-obsidian-and-devonthink](https://axle.design/devonlink-integrate-obsidian-and-devonthink) is invalid as well

**Comment by ryanjamurphy** [comment]
You mean the AppleScript? It's on the article linked at the top of the readme (https://fulcra.design/Posts/DEVONlink-Integrate-Obsidian-with-DEVONthink/).

**Comment by aemsuoqso7816** [comment]
> 

Thank you for your reply, why the link I opened is invalid?
<img width="1108" alt="image" src="https://github.com/ryanjamurphy/DEVONlink-obsidian/assets/140199638/3d1c7d50-0a8f-4258-9209-77f9276219bb">
Can you open this link normally(https://fulcra.design/Posts/DEVONlink-Integrate-Obsidian-with-DEVONthink/))

**Comment by ryanjamurphy** [comment]
I'm not sure, sorry! It is working for me.

**Comment by aemsuoqso7816** [comment]
🙏thanks, i'm trying!
