### ISSUE TITLE
Inserted list of items in Obsidian are not in the same order as that in DT

### ISSUE THREAD

**Issue by wenlzhang** [ryanjamurphy/DEVONlink-obsidian#6]
The inserted list of items in Obsidian are not in the same order as that shown in DT. For instance, DT may give A, B, C, but it becomes A, C, B when inserting them into Obsidian.

Also, is it possible to insert the related items in the form of Markdown link, instead of backlink, if they are not in the same vault of the currently active note in Obsidian? Specifically, I have two Obsidian vaults indexed into the same database in DT. Therefore, it would be great if the items from other Obsidian vaults can be inserted as DT Markdown link or Obsidian URI.

**Comment by ryanjamurphy** [comment]
I'm not sure about why the ordering might change, though I see it too. 

The plugin just uses the default sort order returned by DEVONthink's AppleScript `compare` command. Oddly, the scores seem to be in the right order—so it actually seems to be the concordance list that DEVONthink's showing that's off. In the below screenshot, the left window is the returned items from the plugin command, the middle is the detailed log of the items and their associated score, and the right is the DEVONthink concordance pane. 

![Screen Shot 2021-06-08 at 2 01 13 PM](https://user-images.githubusercontent.com/3618647/121249710-1c2d1980-c862-11eb-95f6-ee88b825ec71.png)
---
I have added a setting for `x-devonthink-item` links in the latest release.

**Comment by wenlzhang** [comment]
Thanks for the detailed explanations!

I have a follow-up question related to the option of inserting `x-devonthink-item`, though. I have two Obsidian vaults, Vault A and Vault B, indexed as two different groups in DT. Therefore, it is possible that when checking related items to Note A in Vault A, notes in Vault B and ordinal DT items would be listed. Therefore, is it possible to achieve this following:

- For note B in Vault A, it would be inserted in the form of Wiki links or `x-devonthink-item` links as they both make sense.
- For note C in Vault B, it would be inserted in the form of `x-devonthink-item` links.
- For item D in regular DT databases, it would also be inserted in the form of `x-devonthink-item` links.

**Comment by ryanjamurphy** [comment]
I think it'd be easy to implement something like what you're describing for items in different DEVONthink databases. It'd be tricky, however, to check if an item is in a different folder in the same database. 

Either way, I think this is the same request as #10—mind adding these thoughts over there?
