### ISSUE TITLE
Vault ID missing

### ISSUE THREAD

**Issue by fongleong** [ryanjamurphy/DEVONlink-obsidian#9]
Hey,
I am currently running obsidian v0.12.3, and I find that the Vault ID is longer stored in the file you mention [here](https://axle.design/devonlink-integrate-obsidian-and-devonthink), can you please point out where it is now? Thanks a lot!

**Comment by ryanjamurphy** [comment]
Good catch. I just updated the script so you don't need the ID. Download it again from the post above, and use the name of your vault instead of the ID. Let me know if it worked!

**Comment by fongleong** [comment]
Every function works well! THANK YOU SOOOO MUCH for the quick adjustment!!

**Comment by ryanjamurphy** [comment]
You're welcome!
